POST http://localhost:8000/api/signup
Content-Type: application/json

{
    "username": "arzael",
    "password": "arzael12",
    "email": "victorpaiva227@gmail.com",
    "nome": "Victor Passos",
    "telefone": "84998984115"
}


###


POST http://localhost:8000/api/login
Content-Type: application/json

{
    "username": "arzael",
    "password": "arzael12"
}


GET http://localhost:8000/test_token
Content-Type: application/json
Authorization: Token d13f275a6a8d2adc023398c557ac224acdce709f
